### ISSUE TITLE
incompatible with Craftbukkit 1.6.4 recommended build

### ISSUE THREAD

**Issue by bluej100** [instructure/BukkitLTI#2]
It would be nice to support 1.6.4. It's currently giving this error for /register:

Aug 20, 2014 10:46:26 PM net.minecraft.server.v1_6_R3.ConsoleLogManager info
INFO: jollup issued server command: /register gq0rvn71oji1roh3n7c68e27ha
Aug 20, 2014 10:46:26 PM net.minecraft.server.v1_6_R3.PlayerConnection handleCommand
SEVERE: null
org.bukkit.command.CommandException: Unhandled exception executing command 'register' in plugin BukkitLTI v0.2.2
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:192)
at org.bukkit.craftbukkit.v1_6_R3.CraftServer.dispatchCommand(CraftServer.java:528)
at net.minecraft.server.v1_6_R3.PlayerConnection.handleCommand(PlayerConnection.java:968)
at net.minecraft.server.v1_6_R3.PlayerConnection.chat(PlayerConnection.java:886)
at net.minecraft.server.v1_6_R3.PlayerConnection.a(PlayerConnection.java:837)
at net.minecraft.server.v1_6_R3.Packet3Chat.handle(SourceFile:49)
at net.minecraft.server.v1_6_R3.NetworkManager.b(NetworkManager.java:296)
at net.minecraft.server.v1_6_R3.PlayerConnection.e(PlayerConnection.java:116)
at net.minecraft.server.v1_6_R3.ServerConnection.b(SourceFile:37)
at net.minecraft.server.v1_6_R3.DedicatedServerConnection.b(SourceFile:30)
at net.minecraft.server.v1_6_R3.MinecraftServer.t(MinecraftServer.java:592)
at net.minecraft.server.v1_6_R3.DedicatedServer.t(DedicatedServer.java:227)
at net.minecraft.server.v1_6_R3.MinecraftServer.s(MinecraftServer.java:488)
at net.minecraft.server.v1_6_R3.MinecraftServer.run(MinecraftServer.java:421)
at net.minecraft.server.v1_6_R3.ThreadServerApplication.run(SourceFile:583)
Caused by: java.lang.NoSuchMethodError: com.instructure.bukkitlti.BukkitLTI.getPlugin(Ljava/lang/Class;)Lorg/bukkit/plugin/java/JavaPlugin;
at com.instructure.bukkitlti.BukkitLTI.getDb(BukkitLTI.java:132)
at com.instructure.bukkitlti.User.where(User.java:81)
at com.instructure.bukkitlti.User.byToken(User.java:89)
at com.instructure.bukkitlti.RegisterCommand.onCommand(RegisterCommand.java:27)
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
... 15 more

**Comment by bluej100** [comment]
Bukkit 1.8 is now out from Spigot, and this is compatible. I don't think 1.6 compatibility is still important.
